"""Build the canopy set from design/canopy/, and generate the wiring.

    python tools/canopy_set.py

Each drawing is named after the hull that flies it: chariot.png is the CHARIOT's
cockpit. A hull with no drawing flies with no cockpit, which the game supports --
there is no default texture and no substitute.

This bakes every drawing that has changed and writes the table that maps a hull to
its canopy, so no C++ has to be edited to add one. Drop a PNG in, run this, done.

Read tools/README.md before you draw one. The two rules that catch people are that
the PNG must be swizzled -- red for the frame, green for the activation regions --
and that the green channel has to cover the whole image, not only where the frame is.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "design", "canopy")
GEN = os.path.join(ROOT, "src", "vg", "generated")

# In ShipClass order, which is what the generated table indexes by. The names are
# the enum's, lowercased: the file name IS the wiring, so this list is the contract
# between the directory and the firmware.
HULLS = ["aegis", "lance", "chariot", "ballista"]


def main():
    if not os.path.isdir(SRC):
        sys.exit("no drawings folder: %s" % SRC)
    if not os.path.isdir(GEN):
        os.makedirs(GEN)

    baker = os.path.join(HERE, "canopy_bake.py")
    rows = []
    for hull in HULLS:
        png = os.path.join(SRC, hull + ".png")
        if not os.path.isfile(png):
            rows.append((hull, None, None))
            continue
        out = os.path.join(GEN, "canopy_%s.h" % hull)
        name = "CANOPY_%s" % hull.upper()

        # Baked only when the drawing is newer than the header. A bake is a few
        # seconds and there is no reason to spend it on three files that have not
        # changed.
        fresh = (os.path.isfile(out)
                 and os.path.getmtime(out) >= os.path.getmtime(png))
        if not fresh:
            print("-- baking %s" % os.path.basename(png))
            r = subprocess.run([sys.executable, baker, png, out, "--name=" + name])
            if r.returncode != 0:
                sys.exit("bake failed for %s" % png)
        else:
            print("-- %s is up to date" % os.path.basename(out))
        rows.append((hull, name, out))

    # ---- the wiring -------------------------------------------------------
    #
    # Generated rather than hand-edited, because the hand-edited version was the one
    # step that was not "drop a file in" -- and nothing stopped a drawing being wired
    # to the wrong hull.
    path = os.path.join(GEN, "canopy_set.h")
    with open(path, "w") as fh:
        fh.write("// GENERATED by tools/canopy_set.py from design/canopy/ -- do not edit.\n")
        fh.write("//\n")
        fh.write("// One row per hull, in ShipClass order. A hull with no drawing gets\n")
        fh.write("// nullptr, which the renderer supports: it flies with no cockpit frame.\n")
        fh.write("// There is no default texture -- a canopy is authored per hull.\n")
        fh.write("#pragma once\n")
        # Resolved relative to THIS header, which sits a directory below the
        # hand-written code it needs.
        fh.write('#include "../vg_canopy.h"\n')
        for hull, name, out in rows:
            if name:
                fh.write('#include "canopy_%s.h"\n' % hull)
        fh.write("\n")
        fh.write("#define VG_CANOPY_SET_ROWS \\\n")
        for i, (hull, name, out) in enumerate(rows):
            end = " \\" if i + 1 < len(rows) else ""
            fh.write("    /* %-8s */ %s,%s\n"
                     % (hull.upper(), ("&" + name) if name else "nullptr", end))
        fh.write("\n")

    print("\ncanopy set:")
    for hull, name, out in rows:
        if name:
            kb = os.path.getsize(out) / 1024.0
            print("  %-9s %-14s %6.0f KB of generated header" % (hull.upper(),
                                                                hull + ".png", kb))
        else:
            print("  %-9s %-14s no cockpit frame" % (hull.upper(), "--"))
    n = sum(1 for _, name, _ in rows if name)
    print("\n%d of %d hulls have a canopy. Wrote %s"
          % (n, len(rows), os.path.relpath(path, ROOT)))


if __name__ == "__main__":
    main()
